# sonar.projectKey=shivmSingh1_mernspace-c-auth-serv
# sonar.organization=shivmsingh1

# sonar.projectName=mernspace-c-auth-serv


# sonar.sources=src

# sonar.tests=src/tests

# sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migrations/**/*

# sonar.qualitygate.wait=true

# sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# sonar.scm.exclusions.disabled=true

sonar.projectKey=shivmSingh1_mernspace-c-auth-serv
sonar.organization=shivmsingh1
sonar.projectName=mernspace-c-auth-serv

sonar.sources=src
sonar.tests=src/tests

sonar.inclusions=src/**/*.ts
sonar.test.inclusions=src/tests/**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/migrations/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
sonar.scm.exclusions.disabled=true